Repository Iam2Jo/Hogwartalk, pull requests merged in 2023-11, with the labels that each got.

#11 T2 15 feature/common component
  app/home/page.tsx
  components/FriendSearchToggle/FriendSearchToggle.styles.ts
  components/FriendSearchToggle/FriendSearchToggle.tsx
  components/FriendSearchToggle/index.ts
  components/Header/Header.styles.ts
  components/Header/Header.tsx
  components/Header/icons/BgmIcon.tsx
  components/Header/icons/ChatIcon.tsx
  components/Header/icons/Icon.styles.ts
  components/Header/icons/LogoutIcon.tsx
  components/Header/icons/MyPageIcon.tsx
  components/Header/icons/SearchIcon.tsx
  components/Header/index.ts
  components/MyPageToggle/MyPageToggle.styles.ts
  components/MyPageToggle/MyPageToggle.tsx
  components/MyPageToggle/index.ts
  custom.d.ts
  next.config.js
  package-lock.json
  package.json
  public/assets/icons/bgm.svg
  public/assets/icons/chat.svg
  public/assets/icons/close.svg
  public/assets/icons/logout.svg
  public/assets/icons/mypage.svg
  public/assets/icons/search.svg
  public/assets/img/HarryPotter.png
  tsconfig.json
Labels: feature

#6 Feat: Add Quiz
  app/layout.tsx
  app/page.tsx
  app/quiz/components/content/Content.styles.ts
  app/quiz/components/content/Content.tsx
  app/quiz/components/content/form/QuizForm.style.ts
  app/quiz/components/content/form/QuizForm.tsx
  app/quiz/components/content/modal/Modal.styles.ts
  app/quiz/components/content/modal/Modal.tsx
  app/quiz/db/QuizData.tsx
  app/quiz/page.styles.ts
  app/quiz/page.tsx
  app/signup/page.tsx
  assets/img/Gryffindor.svg
  assets/img/Hat.svg
  assets/img/Hufflepuff.svg
  assets/img/Logo.svg
  assets/img/Ravenclaw.svg
  assets/img/Slytherin.svg
  assets/img/a.ts
  next.config.js
  package-lock.json
  package.json
  recoil/a.ts
  recoil/atom.ts
Labels: feature

#16 T2 28 feature/chat main
  @types/RESTAPI/createChatting.types.ts
  @types/RESTAPI/editUserInfo.types.ts
  @types/RESTAPI/findAllChatting.types.ts
  @types/RESTAPI/findAllUser.types.ts
  @types/RESTAPI/findMyChatting.types.ts
  @types/RESTAPI/findSpecificUser.types.ts
  @types/RESTAPI/idDuplicateCheck.types.ts
  @types/RESTAPI/inviteChatting.types.ts
  @types/RESTAPI/leaveChatting.types.ts
  @types/RESTAPI/login.types.ts
  @types/RESTAPI/participateChatting.types.ts
  @types/RESTAPI/refreshToken.types.ts
  @types/RESTAPI/signUp.types.ts
  @types/RESTAPI/verifyAuth.types.ts
  @types/Socket/emit/messageToServer.types.ts
  @types/Socket/on/join.types.ts
  @types/Socket/on/leave.types.ts
  @types/Socket/on/messageToClient.types.ts
  @types/Socket/on/messagesToClient.types.ts
  @types/Socket/on/newChat.types.ts
  @types/Socket/on/usersServerToClient.types.ts
  @types/Socket/on/usersToClient.types.ts
  app/selectDormitory/gryffindor/gryffindor.styles.tsx
  app/selectDormitory/gryffindor/gryffindor.tsx
  app/selectDormitory/gryffindor/page.tsx
  app/selectDormitory/hufflepuff/hufflepuff.styles.tsx
  app/selectDormitory/hufflepuff/hufflepuff.tsx
  app/selectDormitory/hufflepuff/page.tsx
  app/selectDormitory/ravenclaw/page.tsx
  app/selectDormitory/ravenclaw/ravenclaw.styles.tsx
  app/selectDormitory/ravenclaw/ravenclaw.tsx
  app/selectDormitory/selectDormitory.tsx
  app/selectDormitory/slytherin/page.tsx
  app/selectDormitory/slytherin/slytherin.styles.tsx
  app/selectDormitory/slytherin/slytherin.tsx
  assets/img/ChevronDown.svg
  assets/img/Hufflepuff.svg
  assets/img/Ravenclaw.svg
  hooks/createChatting.ts
  hooks/createDormitoryIfNone.ts
  hooks/doesDormitoryExist.ts
  hooks/findMyId.ts
  hooks/messageToServer.ts
  hooks/readChatting.ts
  hooks/useChatSocketHooks.ts
  next.config.js
  package-lock.json
  package.json
  utils/a.ts
  utils/scrollUtils.ts
Labels: feature, refactor

#22 T2 30 feature/subchat
  app/selectDormitory/selectDormitory.styles.tsx
  app/selectDormitory/selectDormitory.tsx
  app/tmp/page.tsx
  assets/img/Edit.svg
  assets/img/Invite.svg
  assets/img/InviteAll.svg
  assets/img/Save.svg
  components/ChatRoomInfoModal/ChatRoomInfoModal.styles.ts
  components/ChatRoomInfoModal/ChatRoomInfoModal.tsx
  components/ChatRoomInfoModal/index.ts
  components/InviteToChatRoomModal/InviteToChatRoomModal.styles.ts
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
  components/InviteToChatRoomModal/index.ts
  package-lock.json
  package.json
  recoil/dormChatInfo.ts
  utils/cutStringAfterColon.ts
  utils/extractDateFromString.ts
Labels: feature, design

#25 T2 40 feature/my chatting
  app/selectDormitory/gryffindor/gryffindor.styles.tsx
  app/selectDormitory/gryffindor/gryffindor.tsx
  app/selectDormitory/gryffindor/page.tsx
  app/selectDormitory/hufflepuff/hufflepuff.styles.tsx
  app/selectDormitory/hufflepuff/hufflepuff.tsx
  app/selectDormitory/hufflepuff/page.tsx
  app/selectDormitory/ravenclaw/page.tsx
  app/selectDormitory/ravenclaw/ravenclaw.styles.tsx
  app/selectDormitory/ravenclaw/ravenclaw.tsx
  app/selectDormitory/selectDormitory.tsx
  app/selectDormitory/slytherin/page.tsx
  app/selectDormitory/slytherin/slytherin.styles.tsx
  app/selectDormitory/slytherin/slytherin.tsx
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/Dormitory/index.ts
  components/MyChatting/MyChatting.styles.tsx
  components/MyChatting/MyChatting.tsx
  components/MyChatting/index.ts
  hooks/createDormitoryIfNone.ts
Labels: feature, refactor, design

#27 Feat: 채팅방 생성하기 기능 구현
  app/club/club.tsx
  components/club/chatItem/chatItem.tsx
  components/club/createModal/CreateModal.styles.ts
  components/club/createModal/CreateModal.tsx
  components/club/createModal/page.tsx
  components/club/joinModal/joinModal.tsx
  hooks/RESTAPI/createChatting.type.ts
  hooks/RESTAPI/messageToServer.ts
  hooks/RESTAPI/participateChatting.types.ts
  hooks/RESTAPI/readChatting.ts
  hooks/createChatting.ts
  recoil/chatList.ts
Labels: feature

#30 T2 51 feature/chat header/make dorm info state
  app/selectDormitory/gryffindor/gryffindor.tsx
  app/selectDormitory/hufflepuff/hufflepuff.tsx
  app/selectDormitory/ravenclaw/ravenclaw.tsx
  app/selectDormitory/selectDormitory.tsx
  app/selectDormitory/slytherin/slytherin.tsx
  app/tmp/page.tsx
  hooks/createDormitoryIfNone.ts
  recoil/dormChatId.ts
  recoil/dormChatInfo.ts
Labels: feature

#33 Feat: 채팅방 헤더 추가 및 모달 기능 수정
  app/selectDormitory/gryffindor/gryffindor.tsx
  app/selectDormitory/hufflepuff/hufflepuff.tsx
  app/selectDormitory/ravenclaw/ravenclaw.tsx
  app/selectDormitory/slytherin/slytherin.tsx
  assets/img/More.svg
  assets/img/Person.svg
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
  hooks/useChatSocketHooks.ts
Labels: feature, fix

#32 Refactor: 파일 구조 변경, Design: svg 파일 변경
  app/signup/quiz/db/QuizData.tsx
  app/signup/quiz/page.tsx
  app/signup/quiz/quiz.styles.ts
  app/signup/quiz/quiz.tsx
  assets/img/Gryffindor.svg
  assets/img/Hufflepuff.svg
  assets/img/Ravenclaw.svg
  assets/img/Slytherin.svg
  components/quiz/content/Content.styles.ts
  components/quiz/content/Content.tsx
  components/quiz/form/QuizForm.style.ts
  components/quiz/form/QuizForm.tsx
  components/quiz/modal/Modal.styles.ts
  components/quiz/modal/Modal.tsx
Labels: refactor, design

#34 T2 49 feature/chat header
  app/selectDormitory/gryffindor/gryffindor.tsx
  app/selectDormitory/hufflepuff/hufflepuff.tsx
  app/selectDormitory/ravenclaw/ravenclaw.tsx
  app/selectDormitory/selectDormitory.tsx
  app/selectDormitory/slytherin/slytherin.tsx
  app/tmp/page.tsx
  assets/img/More.svg
  assets/img/Person.svg
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
  hooks/createDormitoryIfNone.ts
  hooks/useChatSocketHooks.ts
  recoil/dormChatId.ts
  recoil/dormChatInfo.ts
Labels: feature, fix

#37 T2 32 feature/common component enhancement
  app/page.tsx
  components/FriendSearchToggle/FriendSearchToggle.styles.ts
  components/FriendSearchToggle/FriendSearchToggle.tsx
  components/Header/Header.tsx
  components/Header/icons/MyPageIcon.tsx
  components/Header/icons/SearchIcon.tsx
  components/MyPageToggle/MyPageToggle.styles.ts
  components/MyPageToggle/MyPageToggle.tsx
Labels: feature

#43 Feat: firefetch hook 구현
  app/selectDormitory/selectDormitory.tsx
  app/tmp/page.tsx
  hooks/createDormitoryIfNone.ts
  hooks/useFireFetch.ts
  utils/firebase.js
Labels: feature

#44 Refactor: 기숙사 정보 recoil state에서 db data로 변경
  components/ChatRoomInfoModal/ChatRoomInfoModal.tsx
  components/Dormitory/Dormitory.tsx
  hooks/createDormitoryIfNone.ts
  package-lock.json
Labels: enhancement

#50 Bug: 채팅 안보이는 버그 수정
  components/Dormitory/Dormitory.tsx
  hooks/useChatSocketHooks.ts
Labels: bug

#53 T2 65 feature/refactor
  app/club/chatting/chatting.tsx
  app/club/chatting/page.tsx
  app/selectDormitory/selectDormitory.tsx
  components/club/chatItem/chatItem.tsx
  components/club/createModal/CreateModal.tsx
  components/club/joinModal/joinModal.tsx
  hooks/createDormitoryIfNone.ts
  hooks/useFireFetch.ts
Labels: feature

#54 Feat: 기숙사 채팅방에서 사용자 초대 모듈 비활성화 및 초대시 유저 정보 db에 저장
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
Labels: feature

#55 T2 68 feature/fix render chatting
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
  hooks/useChatSocketHooks.ts
Labels: feature

#57 T2 55 feature/firebase database integration
  app/home/page.tsx
  components/FriendSearchToggle/FriendSearchToggle.styles.ts
  components/FriendSearchToggle/FriendSearchToggle.tsx
  components/MyPageToggle/MyPageToggle.styles.ts
  components/MyPageToggle/MyPageToggle.tsx
  hooks/useFireFetch.jsx
  package-lock.json
  package.json
  utils/firebase.ts
Labels: feature

#61 Feat: club 채팅방 updateAt 기준 최신순 정렬, 채팅방 등록시 채팅방 이동 기능 추가
  app/club/club.tsx
  components/club/createModal/CreateModal.tsx
  recoil/chatList.ts
Labels: feature

#62 Design: 로그인/ 회원가입 UI 업데이트
  app/club/club.tsx
  app/loginStyle.ts
  app/page.tsx
  app/signup/page.tsx
  app/signup/quiz/components/content/Content.styles.ts
  app/signup/quiz/components/content/Content.tsx
  app/signup/quiz/components/content/form/QuizForm.style.ts
  app/signup/quiz/components/content/form/QuizForm.tsx
  app/signup/quiz/components/content/modal/Modal.styles.ts
  app/signup/quiz/components/content/modal/Modal.tsx
  app/signup/quiz/page.styles.ts
  app/signup/quiz/page.tsx
  app/signup/signupStyle.ts
  components/club/loading/page.tsx
  components/quiz/content/Content.tsx
  recoil/atom.ts
Labels: design

#64 T2 82 feature/debugging
  app/club/chatting/chatting.tsx
  components/Dormitory/Dormitory.tsx
  components/MyChatting/MyChatting.tsx
  components/club/chatItem/chatItem.tsx
  components/club/joinModal/joinModal.tsx
  utils/extractDateFromString.ts
Labels: fix

#67 T2 87 feature/qa debug2/fix modal
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
Labels: feature, fix

#68 Fix: 채팅 안보이는 현상 해결
  app/club/chatting/chatting.tsx
  app/signup/page.tsx
  components/Dormitory/Dormitory.tsx
  components/MyChatting/MyChatting.tsx
  components/club/chatItem/chatItem.tsx
  components/club/createModal/CreateModal.tsx
  components/club/joinModal/joinModal.tsx
Labels: fix

#69 T2 86 feature/qa debug2
  app/club/chatting/chatting.tsx
  app/signup/page.tsx
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
  components/MyChatting/MyChatting.tsx
  components/club/chatItem/chatItem.tsx
  components/club/createModal/CreateModal.tsx
  components/club/joinModal/joinModal.tsx
Labels: feature, fix

#71 T2 77 feature/refactor friendsearch toggle
  components/FriendSearchToggle/FriendSearchToggle.tsx
  utils/firebase.ts
Labels: refactor

#76 T2-93-feature/qa-debug3/debug
  app/selectDormitory/selectDormitory.tsx
  components/Dormitory/Dormitory.tsx
Labels: feature, fix

#73 Design: 채팅방 css 깨짐 해결 및 candle.svg 용량 줄이기, Fix: BGM 안들리는 현상 수정
  app/club/club.styles.ts
  app/club/club.tsx
  app/home/page.tsx
  app/layout.tsx
  assets/img/Candles.svg
  components/BgmPlayer/bgmPlayer.tsx
  components/Dormitory/Dormitory.styles.tsx
  components/MyChatting/MyChatting.styles.tsx
Labels: design

#74 Feat: 나가기 누르면 club 목록으로 이동
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/club/createModal/CreateModal.tsx
Labels: feature, refactor

#75 Doc: README.md 작성
  README.md
Labels: documentation

#77 T2 92 feature/qa debug3
  app/selectDormitory/selectDormitory.tsx
  components/Dormitory/Dormitory.tsx
Labels: feature, fix

#78 Feat: 기숙사 채팅방 못나가게 설정
  components/ChatRoomInfoModal/ChatRoomInfoModal.tsx
  components/Dormitory/Dormitory.tsx
Labels: feature

#80 Fix: 친구목록 접속 유무 표시 안되는 에러 수정
  components/FriendSearchToggle/FriendSearchToggle.tsx
  hooks/useChatSocketHooks.ts
Labels: fix

#81 T2 98 feature/qa debug4
  components/ChatRoomInfoModal/ChatRoomInfoModal.tsx
  components/Dormitory/Dormitory.tsx
  components/FriendSearchToggle/FriendSearchToggle.tsx
  hooks/useChatSocketHooks.ts
Labels: fix

#82 T2 89 feature/refactor UI
  components/Dormitory/Dormitory.styles.tsx
  components/Dormitory/Dormitory.tsx
  components/MyChatToggle/MyChatToggle.styles.ts
  components/MyChatting/MyChatting.styles.tsx
  components/MyPageToggle/MyPageToggle.styles.ts
Labels: refactor, design

#93 Feat: 접속 유저 목록에 기숙사 정보 추가
  components/FriendSearchToggle/FriendSearchToggle.tsx
Labels: feature

#94 T2 104 feature/add dorm info
  components/FriendSearchToggle/FriendSearchToggle.tsx
Labels: feature
